options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 127
  driver: "ros2_canopen::LifecycleMasterDriver"
  package: "canopen_master_driver"
  baud_rate: 500
  heartbeat_consumer: true
  heartbeat_producer: 1000
  boot_timeout: 10000
  # sync_period: 100000 # 100ms

defaults:
  heartbeat_consumer: true
  heartbeat_producer: 1000
  
nodes:
  packaging_machine_1:
    node_id: 32
    dcf: "packaging_machine.eds"
    driver: "ros2_canopen::LifecycleProxyDriver" 
    package: "canopen_proxy_driver"
    reset_communication: false
    boot: false
    sdo_timeout_ms: 80

  packaging_machine_2:
    node_id: 33
    dcf: "packaging_machine.eds"
    driver: "ros2_canopen::LifecycleProxyDriver" 
    package: "canopen_proxy_driver"
    reset_communication: false
    boot: false
    sdo_timeout_ms: 80

  # packaging_machine_1_squeezer:
  #   node_id: 60
  #   dcf: "C20-120L2C_V1.02.eds"
  #   driver: "ros2_canopen::LifecycleProxyDriver" 
  #   package: "canopen_proxy_driver"
  #   reset_communication: false
  #   boot: false
  #   sdo:
  #     - {index: 0x2000, sub_index: 1, value: 7}
  # packaging_machine_1_conveyer:
  #   node_id: 61
  #   dcf: "C20-120L2C_V1.02.eds"
  #   driver: "ros2_canopen::LifecycleProxyDriver" 
  #   package: "canopen_proxy_driver"
  #   reset_communication: false
  #   boot: false
  #   sdo:
  #     - {index: 0x2000, sub_index: 2, value: 0}
  #     - {index: 0x2000, sub_index: 1, value: 5}
  #     - {index: 0x2000, sub_index: 1, value: 7}

  # packaging_machine_2_squeezer:
  #   node_id: 62
  #   dcf: "C20-120L2C_V1.02.eds"
  #   driver: "ros2_canopen::LifecycleProxyDriver" 
  #   package: "canopen_proxy_driver"
  #   reset_communication: false
  #   boot: false
  #   sdo:
  #     - {index: 0x2000, sub_index: 1, value: 7}
  # packaging_machine_2_conveyer:
  #   node_id: 63
  #   dcf: "C20-120L2C_V1.02.eds"
  #   driver: "ros2_canopen::LifecycleProxyDriver" 
  #   package: "canopen_proxy_driver"
  #   reset_communication: false
  #   boot: false   
  #   sdo:
  #     - {index: 0x2000, sub_index: 2, value: 0}
  #     - {index: 0x2000, sub_index: 1, value: 5}
  #     - {index: 0x2000, sub_index: 1, value: 7}


